=== andrewshawcare/contact-list/src/schemas/contact.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "firstName": { "type": "string" },
    "lastName": { "type": "string" },
    "title": { "type": "string" },
    "address": { "type": "string" },
    "city": { "type": "string" },
    "province": { "type": "string" }
  },
  "required": [ "id", "firstName", "lastName", "title", "address", "city", "province" ]
}

=== andrewshawcare/contact-list/src/contacts.json
[
    {
        "id": "1",
        "firstName": "Amy",
        "lastName": "Jones",
        "title": "Sales Representative",
        "address": "372 Harbord Street",
        "city": "Toronto",
        "province": "Ontario"
    },
    {
        "id": "2",
        "firstName": "James",
        "lastName": "King",
        "title": "President and CEO",
        "address": "2 Bloor Street East",
        "city": "Toronto",
        "province": "Ontario"
    },
    {
        "id": "3",
        "firstName": "Ray",
        "lastName": "Moore",
        "title": "Vice President of Sales",
        "address": "375 Church Street",
        "city": "Mississauga",
        "province": "Ontario"
    },
    {
        "id": "4",
        "firstName": "John",
        "lastName": "Williams",
        "title": "Vice President of Engineering",
        "address": "237 Dundas Street East",
        "city": "Brampton",
        "province": "Ontario"
    },
    {
        "id": "5",
        "firstName": "Joe",
        "lastName": "Doe",
        "title": "Sales Representative",
        "address": "3023 Parkerhill Road",
        "city": "Mississauga",
        "province": "Ontario"
    }
]

=== andrewshawcare/contact-list/src/application/default-contacts.json
[
    {
        "id": "fdf49196-1e9a-420a-958f-0a7dca60a2e2",
        "firstName": "Amy",
        "lastName": "Jones",
        "title": "Sales Representative",
        "address": "372 Harbord Street",
        "city": "Toronto",
        "province": "Ontario"
    },
    {
        "id": "07c54859-dbd4-4747-8e8f-73f8d144f082",
        "firstName": "James",
        "lastName": "King",
        "title": "President and CEO",
        "address": "2 Bloor Street East",
        "city": "Toronto",
        "province": "Ontario"
    },
    {
        "id": "9dc0f980-2375-4cea-ab59-441e6fb3234c",
        "firstName": "Ray",
        "lastName": "Moore",
        "title": "Vice President of Sales",
        "address": "375 Church Street",
        "city": "Mississauga",
        "province": "Ontario"
    },
    {
        "id": "77510c38-3c14-457c-8321-3781702eb2b2",
        "firstName": "John",
        "lastName": "Williams",
        "title": "Vice President of Engineering",
        "address": "237 Dundas Street East",
        "city": "Brampton",
        "province": "Ontario"
    },
    {
        "id": "df628d58-fbb0-42a6-8068-3585b993f987",
        "firstName": "Joe",
        "lastName": "Doe",
        "title": "Sales Representative",
        "address": "3023 Parkerhill Road",
        "city": "Mississauga",
        "province": "Ontario"
    }
]
